version: '3.8'

services:
  # --- SERVICIO DE LA APLICACIÓN ---
  reservas-service:
    build: .
    container_name: reservas-service-app
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-db
      - rabbitmq-broker
    networks:
      - reservas-net

  # --- BASE DE DATOS POSTGRES ---
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: reservas_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reservas-net

  rabbitmq-broker:
    image: rabbitmq:3.11-management # Usamos la imagen con la UI de gestión
    container_name: rabbitmq-broker
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"   # Puerto del broker para la aplicación
      - "15672:15672" # Puerto para la interfaz web de gestión
    networks:
      - reservas-net

# Volumen persistente para la base de datos
volumes:
  postgres_data:

# Red interna
networks:
  reservas-net:
    driver: bridge
